### ISSUE TITLE
Github::Meta output wrong info when repository is fork

### ISSUE THREAD

**Issue by pavelsr** [ghedo/p5-Dist-Zilla-Plugin-GitHub#53]
I got wrong metadata for my repository, https://github.com/pavelsr/net-ip-checker using `[Github::Meta]` plugin, it showed links from forked repository.

E.g. META.yml looked as

```yaml
---
abstract: 'IPv4/IPv6 addresses validator'
author:
  - 'Pavel Serikov <pavelsr@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-IP-Checker
requires:
  Exporter: '0'
  Regexp::IPv4: '0'
  Regexp::IPv6: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/bingos/net-ip-minimal/issues
  homepage: http://metacpan.org/release/Net-IP-Minimal
  repository: git://github.com/bingos/net-ip-minimal.git
version: '0.01'
x_serialization_backend: 'YAML::Tiny version 1.70'
```

Solved by migrating to alternative plugin, https://metacpan.org/pod/Dist::Zilla::Plugin::GithubMeta, but still please have a look
